### ISSUE TITLE
Overlay not working after recent RL update

### ISSUE THREAD

**Issue by hjdarnel** [hong-niu/runelite-birdhouse-overlay#6]
Hello!

I noticed recently that this plugin doesn't seem to work anymore.

For context, I'm launching RuneLite via the Jagex launcher. The magic birdhouses I'm using are either showing "unbuilt" or "unseeded" regardless of the state. I'm not sure if the plugin needs to be patched to work with the updated client or not.

**Comment by jevonsp** [comment]
Yeah I'm on runelite w/o launcher and its also not working.

**Comment by li-cody** [comment]
Hi folks, thanks for bringing this to our attention. @hong-niu and I haven't played RS in a while and we're both a little busy with other obligations, so we might not be able to get around to this for a bit (maybe not until next week at the earliest). Y'all are welcome to submit a PR for a fix since the code isn't terribly complicated. Thanks and appreciate you all for using this plugin!

**Comment by dy46** [comment]
@li-cody looking forward to the fix!

**Comment by edl13** [comment]
@li-cody would you consider using blue instead of green for the indicator? I know this is off topic for the thread but this this is imporatnant

**Comment by edl13** [comment]
because of colonblind

**Comment by dominio50** [comment]
@edl13 You can change the color of the overlay in the settings.
